version: "3"

services:
    backend:
        container_name: backend
        build:
            context: ./backend
            dockerfile: Dockerfile
        ports:
            - "5000:5000"
        networks:
            - web
    frontend:
        container_name: frontend
        build:
            context: ./frontend
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        networks:
            - web
networks:
    web:

