version: "3"

services:
    backend:
        container_name: backend
        build:
            context: ./backend
            dockerfile: Dockerfile
        ports:
            - "5000:5000"
    frontend:
        container_name: frontend
        build:
            context: ./frontend
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        depends_on:
            - backend